server:
  port: 9120

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: http://localhost:9001
          predicates:
            - Path=/api/v1/books/**
          filters:
            - AuthFilter
        - id: employee-service
          uri: http://localhost:9002
          predicates:
            - Path=/api/v1/employees/**
          filters:
            - AuthFilter
        - id: borrowing-service
          uri: http://localhost:9003
          predicates:
            - Path=/api/v1/borrowing/**
        - id: user-service
          uri: http://localhost:9004
          predicates:
            - Path=/api/v1/users/**
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"